### ISSUE TITLE
keep local config in local folder

### ISSUE THREAD

**Issue by Akuukis** [gata1526/TheCorporation.space#3]
Don't use `/etc/config.json`, use `./config.json`. No need for sudo anymore :)

Also take a look into bash env files - gitignored `.env` and commited `.env.example` - which is quite a standard way to do configuration but json is totally fine too.

**Comment by Akuukis** [comment]
Also no need for `sudo touch /etc/config.json`, `nano` will create the file if one didn't exist

**Comment by gata1526** [comment]
The config are outside the folder in the server to prevent user to access it without authorization.
