### ISSUE TITLE
python vs python3

### ISSUE THREAD

**Issue by Akuukis** [gata1526/TheCorporation.space#4]
Is this project python2 or python3 compatible, or both? For me (Ubuntu 20.04.2 LTS) there's no `pip`, only `pip3`. 

I'd suggest to use a specific version, e.g. `pip3` and `python3` in place of `pip` and `python`.

**Comment by gata1526** [comment]
It's all last gen. It's easier to install only python 3.9 and remove the other to prevent pip to install to the wrong version
