### ISSUE TITLE
explain the config

### ISSUE THREAD

**Issue by Akuukis** [gata1526/TheCorporation.space#8]
Most keys in the config are not straightforward how to fill. I just want to see something in my browser, do I even need all of that to get there?

Per each key please elaborate on
- optional or not, and what's not gonna work if it's missing
- how to get it (e.g. go there, do this, do that, etc.)
- example value (so that I don't mess up formatting, casing, etc.)

Right now I'm even confused whenever DISCORD_ID is just my discord nickname, or nickname together withe the hash, or something else entirely.

**Comment by gata1526** [comment]
I will try to make it most straightforward, but you need all those setting to start the application without it, there will be an error.

**Comment by gata1526** [comment]
Discord id is an API id that you need to get from the discord developer manager

**Comment by gata1526** [comment]
Flask have a lot of documentation online. Simply check one of the setting in google and you should get a good idea of what you need

**Comment by Akuukis** [comment]
Checking documentation is a thing every good dev will do, which comes *after* launching a working server/app. I can't do anything if I have not launched it - most importantly can't preview the effects of changes I made (after reading docs). 

In README, *always* walk through the reader how to launch it. The less steps and closer to copy/paste the better. If there's project-specific gotchas that ofc aren't covered on docs, how I'm supposed to solve them by reading the docs? And how I'm supposed to guess if there's any, or how many?

Once the thing works on my PC, and I do something to break it, then it's on me.
